/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Answer.Digital;

import java.io.IOException;

public class App {

    private static Store store = new Store();

    public static void main(String[] args) throws IOException {
        System.out.println(Sku.lineParse("H57\tTin o Beans\t1.23"));

        store.fileParse("C:\\Users\\alexr\\OneDrive\\Documents\\Project\\Answer-Digital\\src\\main\\resources\\sku-list.txt");

        System.out.println(store.getSkuList());
    }
}