/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Answer.Digital;

public class App {

    private final Store store = new Store();

    public static void main(String[] args) {
        System.out.println(Sku.lineParser("H57\tTin o Beans\t1.23"));
    }
}